import { createTheme } from '@shopify/restyle';
import fonts from './fonts';
import palette from './palette';

const theme = createTheme({
  colors: {
    lightBg: palette.lightBg,
    mainBackground: palette.white,
    mainForeground: palette.tiber,
    black: palette.black,
    cardBackground: palette.grey,
    cardBackgroundHighlight: palette.alto,
    cardForeground: palette.tiber,
    cardBorder: palette.fog,
    light: palette.grayText,
    imagePlaceholder: palette.loblolly,
    facebook: palette.facebook,
    headerBackground: palette.tiber,
    headerBackgroundHighlight: palette.tiberDark,
    headerForeground: palette.white,
    lightbg: palette.lightBg,
    authHeaderBackground: palette.white,
    authHeaderForeground: palette.fiord,
    transparent: palette.transparent,
    border: palette.lightGrey,
    submitted: palette.submitted,
    lightsubmitted: palette.submittedLight,
    lightBorder: palette.grey,
    gray: palette.gray,
    tabBarInvactive: palette.manatee,
    tabBarActiveBackground: palette.grey,
    lightPink: palette.lightPink,
    pink: palette.pink,
    text: palette.bermudaGrey,
    accentText: palette.tiber,
    headingText: palette.fiord,
    textOnPrimary: palette.white,
    inputLabelText: palette.tiberDark,
    inputText: palette.regentGrey,
    inputPlaceholder: palette.bermudaGrey,
    activeBooking: palette.lightBlue,
    buttonDisabled: palette.lightGrey,
    buttonDisabledText: palette.darkGrey,
    lightBordernew: palette.lightGreyBorder,
    callControlButton: palette.red,
    lightG: '#777470',
    primary: palette.primary,
    primaryHighlight: palette.greenDark,
    secondary: palette.amaranth,
    secondaryHighlight: palette.amaranthDark,
    success: palette.lightGreen,
    warning: palette.yellow,
    danger: palette.red,
    neutral: palette.grey,
    green: palette.green,
  },
  spacing: {
    xxs: 0,
    xs: 3,
    s: 10,
    m: 16,
    l: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadii: {
    s: 7,
    xs: 10,
    xm: 12,
    m: 16,
    l: 24,
    xl: 32,
  },
  breakpoints: {},
  textVariants: {
    header: {
      fontWeight: '700',
      fontSize: 16,
      fontFamily: fonts.PoppinsMedium,
      lineHeight: 24,
      color: 'primary',
      textAlign: 'center',
    },
    body: {
      fontWeight: '400',
      fontSize: 14,
      fontFamily: fonts.PoppinsRegular,
    },
    authHeader: {
      fontSize: 22,
      fontWeight: '600',
      fontFamily: fonts.PoppinsBold,
    },
    inputLabel: {
      fontSize: 14,
      fontWeight: '400',
      marginBottom: 's',
      lineHeight: 14,
      fontFamily: fonts.PoppinsRegular,
    },
    caption: {
      fontSize: 10,
      fontWeight: '500',
      fontFamily: fonts.PoppinsRegular,
    },
    buttonLabel: {
      fontSize: 14,
      lineHeight: 21,
      fontWeight: '500',
      textAlign: 'center',
      fontFamily: fonts.PoppinsMedium,
    },
    listItemTitle: {
      fontSize: 14,
      lineHeight: 21,
      fontWeight: '400',
      letterSpacing: 0.9,
      fontFamily: fonts.PoppinsRegular,
    },
    sectionHeading: {
      fontSize: 14,
      lineHeight: 21,
      fontWeight: '600',
      letterSpacing: 1,
      fontFamily: fonts.PoppinsRegular,
    },
    modalTitle: {
      fontSize: 16,
      fontWeight: '500',
      fontFamily: fonts.PoppinsMedium,
    },
    modalButton: {
      fontSize: 15,
      fontWeight: '500',
      fontFamily: fonts.PoppinsRegular,
    },
  },
});

export type Theme = typeof theme;
export default theme;
